# Generated by Django 4.2 on 2023-04-20 17:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musician_employee_address_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[app.models.validate_geeks_mail]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
